AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'com.amazon.ask.trivia.TriviaSkillLambda::handleRequest'
      CodeUri: target/trivia-1.0-jar-with-dependencies.jar
      Runtime: java8
      MemorySize: 512
      Timeout: 60
      Policies: AWSLambdaBasicExecutionRole
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill